import pandas as pd
df=pd.read_csv('indian_election.csv')
df.rename(columns={'st_name':'State','cand_name':'Candidate_name','cand_sex':'Gender','totvotpoll':'total_vote_received','electors':'No._of_voters'},inplace=True)
df.drop(columns=['partyabbre','Candidate_name','pc_name','pc_no'],axis=1,inplace=True)
df.drop_duplicates(inplace=True)
df.rename(columns={'pc_type':'Constituency_reservation_status'},inplace=True)
df.dropna(subset=['Gender'],inplace=True)
df['State']=df['State'].astype('string')
df['year']=df['year'].astype('string')
df['Constituency_reservation_status']=df['Constituency_reservation_status'].astype('string')
df['Gender']=df['Gender'].astype('string')
df['partyname']=df['partyname'].astype('string')
df['Constituency_reservation_status']=df['Constituency_reservation_status'].fillna('General')
df.to_csv('Indian_election_cleandata.csv',index=False)